### ISSUE TITLE
编译是显示找不到GeographicLibConfig.cmake，按网上教程安装了GeographicLib，还是找不到GeographicLibConfig.cmake，

### ISSUE THREAD

**Issue by feizaihui-ins** [libing64/pose_ekf#10]
![image](https://user-images.githubusercontent.com/66055555/98759446-0fe7f780-240c-11eb-9a2d-51e74c327f04.png)
编译是显示找不到GeographicLibConfig.cmake，按网上教程安装了GeographicLib，还是找不到GeographicLibConfig.cmake，或者geographiclib-config.cmake

**Comment by libing64** [comment]
GeographicLib has been removed from the dependance, and rtklib is used to convert from LLA to NED frame.
