### ISSUE TITLE
咨询 F G的求法

### ISSUE THREAD

**Issue by taoyang1994** [libing64/pose_ekf#3]
您好，打扰一下，我在学习您写的pose_ekf，对F矩阵，G矩阵的求法，不太理解，感觉和ESKF中的求法不一样，我看了您提供的参考资料Quaternion and Rotation 也没有找到，还有correct_gravity这一块也不理解，您能提供一下有关F G矩阵的求法和correct_gravity的理论资料吗？万分感谢。谢谢

![1](https://user-images.githubusercontent.com/29836389/37212199-51300582-23e9-11e8-8086-18e268aa8b00.jpg)
![2](https://user-images.githubusercontent.com/29836389/37212734-d761063c-23ea-11e8-8cdb-63f48806ad5e.jpg)

**Comment by waihekor** [comment]
最下面的参考文档中有的

**Comment by libing64** [comment]
ekf has changed to error state kf
