### ISSUE TITLE
关于坐标系的请教

### ISSUE THREAD

**Issue by jinxiao1231** [libing64/pose_ekf#6]
你好，花了较多的时间阅读这边的代码，有几个问题一直想不通，希望得到指点：
1.我在conversion.cpp文件中看到旋转矩阵表示的是body-ned， 我想问一下这里的世界坐标系是否是ned？ 如果世界坐标系是ned，那磁力计在导航系下观测到的应该是[a, 0, b]，为何代码中却说pose_ekf.cpp中却说should be [0, 1， x]

2.同样的问题，GPS数据后应该先将其转换到椭球系下，那边的转换方向是否有误？ 转换完后又转换到local cartesian coordinates(这个应该是东北天吧？)，，，之后得到的locX\locY\locZ应该都是处于enu坐标系下，应该将其转换到ned下，为啥变换却是：
  position(0) = locY;
  position(1) = -locX;
  position(2) = locZ;

麻烦了～

**Comment by libing64** [comment]
pose_ekf has been reimplemented and reference frame changes to NED.
