### ISSUE TITLE
hector_uav_msgs/Altimeter.h No such file or directory

### ISSUE THREAD

**Issue by shikouchen** [libing64/pose_ekf#7]
> hector_uav_msgs/Altimeter.h No such file or directory

Do I need to install other package?

**Comment by DepeiYan** [comment]
I have met the same problem, how can I do?

**Comment by jssf1020** [comment]
use ubuntu 14.04,use apt-get install hector_uav_msgs,copy Altimeter.h  from the opt/ros/indigo/include/hector_uav_msgs to ubuntu 16.04 
because ubuntu 16.04 cannot use apt to get hector_uav_msgs

**Comment by 863217373** [comment]
Can you update Altimeter.h to github， because I don't have a computer operated by ubuntu 14.04. @jssf1020

**Comment by 863217373** [comment]
> use ubuntu 14.04,use apt-get install hector_uav_msgs,copy Altimeter.h from the opt/ros/indigo/include/hector_uav_msgs to ubuntu 16.04
> because ubuntu 16.04 cannot use apt to get hector_uav_msgs

Can you update Altimeter.h to github， because I don't have a computer operated by ubuntu 14.04. @jssf1020

**Comment by libing64** [comment]
hector_uav_msgs dependance has been removed from the code.
