### ISSUE TITLE
我觉得你的diff_qvqstar_q函数写错了

### ISSUE THREAD

**Issue by waihekor** [libing64/pose_ekf#9]
![QQ截图20200313175125](https://user-images.githubusercontent.com/16462372/76610711-4820f880-6554-11ea-878e-8ca351b7135d.png)
![QQ截图20200313175457](https://user-images.githubusercontent.com/16462372/76610719-4ce5ac80-6554-11ea-8449-444b02dcae30.png)

你好，我看了你的代码，觉得代码中的函数diff_qvqstar_q，即速度误差对四元数误差的雅克比矩阵有点问题，我求得第一列和你的是一样的，其它都比你多出一项，希望能得到你的解答，谢谢

**Comment by libing64** [comment]
The ekf has changed to error-state kf to improve the accuracy.
